FROM iglucontest/gridworld_env:latest

RUN pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116
#RUN pip3 install git+https://github.com/iglu-contest/sample-factory.git
RUN pip3 install sample-factory==1.121.3

ENV CUDA_VISIBLE_DEVICES="0,1"
RUN pip install "pydantic>=1.8.2" "wandb>=0.12.0" "matplotlib"